### ISSUE TITLE
TWI pins for the UPduino don't match neorv32 top-level

### ISSUE THREAD

**Issue by mabembedded** [stnolting/neorv32-setups#124]
The TWI pins for the UPduino top level are marked as inout:
```
    twi_sda_io  : inout std_logic;
    twi_scl_io  : inout std_logic;
```
But, the CPU top-level has separate input and output pins for the SDA and SCL lines:
```
    twi_sda_i      : in  std_ulogic := 'H'; -- serial data line sense input
    twi_sda_o      : out std_ulogic; -- serial data line output (pull low only)
    twi_scl_i      : in  std_ulogic := 'H'; -- serial clock line sense input
    twi_scl_o      : out std_ulogic; -- serial clock line output (pull low only)
``` 
How would you advise reconciling this difference?

**Comment by stnolting** [comment]
This is another issue of the outdated Radiant setup. The TWI's tri-state drivers have been moved-out of the SoC as they caused troubles with some synthesis tools when "buried" too deep. Now you'll need to create the tri-state circuitry right at the top entity hierarchy level (see [https://stnolting.github.io/neorv32/#_two_wire_serial_interface_controller_twi](https://stnolting.github.io/neorv32/#_two_wire_serial_interface_controller_twi)).

I have already updated the Radiant setup for the UPduino - I just need to verify and upload it :wink:

**Comment by stnolting** [comment]
The UpDunio Radiant project is now up-to-date:
* update NEORV32 rtl file list
* add TWI tri-state drivers
* update SPRAM memory files (#122)

**Comment by mabembedded** [comment]
The updates work - thanks!
