### ISSUE TITLE
Add Arty 35t & 100t support [implementation]

### ISSUE THREAD

**Issue by Unike267** [stnolting/neorv32-setups#162]
Hi @stnolting 

According to what we discussed the other day:

> It occurs to me that maybe the arty option can be added to the CI list of implementations.
That would be awesome! Feel free to propose a PR for that 😉

I've made the following container:

- `ghcr.io/unike267/containers/impl-arty:latest`

With:

- `GHDL + yosys + GHDL yosys plugin + nextpnr-xilinx + prjxray`

To perform `synthesis + implementation + generate bitstream` on the boards:

- `Arty A7 35t`  
- `Arty A7 100t` 

I've built and pushed this container through continuous integration in the repository:

- `gh: Unike267/Containers` 

I've tested the `synthesis + implementation + generate bitstream` of the NEORV32 in the branch:

- `Unike267/Containers/tree/neorv32-setups`

And as we can see in these [jobs](https://github.com/Unike267/Containers/actions/runs/8456020095) the bitstreams are generated correctly.

I've tested them on Arty A7 35t & 100t and they work fine.

---

Now the challenge is to add these implementations through the CI of the `neorv32-setups` repository. 

But before starting this work we should wonder, is this implementation really useful? :thinking: 

I mean, the implementation is limited because dsp can't be used. The yosys options `-nodsp` and `-nolutram` are necessary to perform the implementation.

However, if you are really interested in implementing this option, I could try to solve the challenge of adding arty support through continuous integration of the `neorv32-setups`.

In my opinion it would be interesting to support Xilinx implementation through FOSS tools. 

What do you think?

---

/cc @umarcor

**Comment by stnolting** [comment]
Hey @Unike267!

I think it would be really great to have support for an open-source Xilinx flow here! DSPs are a nice feature, but we don't really need them for a simple core configuration (e.g. `FAST_MUL_EN => false`).

> In my opinion it would be interesting to support Xilinx implementation through FOSS tools.

Full ACK! :+1:

**Comment by Unike267** [comment]
Hi @stnolting!

> I think it would be really great to have support for an open-source Xilinx flow here! DSPs are a nice feature, but we don't really need them for a simple core configuration (e.g. FAST_MUL_EN => false).

Okey perfect! 

When I have a moment I will do a PR. Now I'm a little bit busy writing my master thesis 😅 but don't worry I won't forget it.

For the moment I think that we can close this issue.

Thanks for your opinion! 😄

**Comment by stnolting** [comment]
Awesome!

Just take your time :wink:
