### ISSUE TITLE
setup iCESugar-v1.5 failed

### ISSUE THREAD

**Issue by wklam296** [stnolting/neorv32-setups#70]
yosys  \\
  -p \\
  "ghdl --std=08 --workdir=build -Pbuild --no-formal neorv32_iCESugarv15_BoardTop_MinimalBoot; \\
   synth_ice40 \\
  -top neorv32_iCESugarv15_BoardTop_MinimalBoot -dsp \\
  -json neorv32_iCESugar-v1.5_MinimalBoot.json" 2>&1 | tee yosys-report.txt
ERROR: No such command: ghdl (type 'help' for a command overview)
nextpnr-ice40 \\
  --up5k --package sg48 --ignore-loops --timing-allow-fail \\
  --pcf ../constraints/board/iCESugar-v1.5/constraints.pcf \\
  --json neorv32_iCESugar-v1.5_MinimalBoot.json \\
  --asc neorv32_iCESugar-v1.5_MinimalBoot.asc 2>&1 | tee nextpnr-report.txt
ERROR: Failed to open JSON file 'neorv32_iCESugar-v1.5_MinimalBoot.json'.

**Comment by wklam296** [comment]
[osflow/synthesis.mk](https://github.com/stnolting/neorv32-setups/blob/main/osflow/synthesis.mk)

The setup want to use yosys-ghdl plug-in but not default using it.
Line 19 : **-p \** should be **-m ghdl -p \**

**Comment by umarcor** [comment]
See https://github.com/ghdl/ghdl-yosys-plugin/issues/182#issuecomment-1357390794. Precisely https://github.com/stnolting/neorv32-setups/blob/main/osflow/common.mk#L20. So, try `GHDL_PLUGIN_MODULE=ghdl make BOARD=iCEBreaker UP5KDemo`.

**Comment by stnolting** [comment]
@wklam296 can we close this? ;)

**Comment by wklam296** [comment]
> @wklam296 can we close this? ;)

sure, thanks
